// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm } from "emdash";

export interface PageInhaltEinstiegV1Block {
  _type: "einstieg";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
  "hinweis"?: string | null;
}

export type PageInhaltEinstiegBlock = PageInhaltEinstiegV1Block;

export interface PageInhaltPinnwandV1Block {
  _type: "pinnwand";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
  "zettel": { "vorne": string; "vorne_klein"?: string | null; "hinten": string; "farbe"?: "papier" | "senf" | "rosa" | null }[];
}

export type PageInhaltPinnwandBlock = PageInhaltPinnwandV1Block;

export interface PageInhaltPlanspielV1Block {
  _type: "planspiel";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
}

export type PageInhaltPlanspielBlock = PageInhaltPlanspielV1Block;

export interface PageInhaltWahrheitstestV1Block {
  _type: "wahrheitstest";
  _version: 1;
  _key: string;
  "titel": string;
  "frage"?: string | null;
  "aufloesung"?: string | null;
  "text"?: string | null;
}

export type PageInhaltWahrheitstestBlock = PageInhaltWahrheitstestV1Block;

export interface PageInhaltNachtV1Block {
  _type: "nacht";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
}

export type PageInhaltNachtBlock = PageInhaltNachtV1Block;

export interface PageInhaltEinwaendeV1Block {
  _type: "einwaende";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
  "punkte"?: { "symbol": "kasse" | "uhr" | "drucker" | "lupe"; "text": string }[] | null;
}

export type PageInhaltEinwaendeBlock = PageInhaltEinwaendeV1Block;

export interface PageInhaltFrueherV1Block {
  _type: "frueher";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
  "bildunterschrift"?: string | null;
}

export type PageInhaltFrueherBlock = PageInhaltFrueherV1Block;

export interface PageInhaltKassenzettelV1Block {
  _type: "kassenzettel";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
  "link"?: string | null;
}

export type PageInhaltKassenzettelBlock = PageInhaltKassenzettelV1Block;

export interface PageInhaltPreisTeaserV1Block {
  _type: "preis_teaser";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
  "link"?: string | null;
}

export type PageInhaltPreisTeaserBlock = PageInhaltPreisTeaserV1Block;

export interface PageInhaltSchlussV1Block {
  _type: "schluss";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
  "nachsatz"?: string | null;
}

export type PageInhaltSchlussBlock = PageInhaltSchlussV1Block;

export type PageInhaltBlock = PageInhaltEinstiegBlock | PageInhaltPinnwandBlock | PageInhaltPlanspielBlock | PageInhaltWahrheitstestBlock | PageInhaltNachtBlock | PageInhaltEinwaendeBlock | PageInhaltFrueherBlock | PageInhaltKassenzettelBlock | PageInhaltPreisTeaserBlock | PageInhaltSchlussBlock;

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  inhalt?: PageInhaltBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
  }
}