// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm } from "emdash";

export interface PageInhaltEinstiegV1Block {
  _type: "einstieg";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
  "hinweis"?: string | null;
}

export type PageInhaltEinstiegBlock = PageInhaltEinstiegV1Block;

export interface PageInhaltPinnwandV1Block {
  _type: "pinnwand";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
  "zettel": { "vorne": string; "vorne_klein"?: string | null; "hinten": string; "farbe"?: "papier" | "senf" | "rosa" | null }[];
}

export type PageInhaltPinnwandBlock = PageInhaltPinnwandV1Block;

export interface PageInhaltPlanspielV1Block {
  _type: "planspiel";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
}

export type PageInhaltPlanspielBlock = PageInhaltPlanspielV1Block;

export interface PageInhaltWahrheitstestV1Block {
  _type: "wahrheitstest";
  _version: 1;
  _key: string;
  "titel": string;
  "frage"?: string | null;
  "aufloesung"?: string | null;
  "text"?: string | null;
}

export type PageInhaltWahrheitstestBlock = PageInhaltWahrheitstestV1Block;

export interface PageInhaltNachtV1Block {
  _type: "nacht";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
}

export type PageInhaltNachtBlock = PageInhaltNachtV1Block;

export interface PageInhaltEinwaendeV1Block {
  _type: "einwaende";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
  "punkte"?: { "symbol": "kasse" | "uhr" | "drucker" | "lupe"; "text": string }[] | null;
}

export type PageInhaltEinwaendeBlock = PageInhaltEinwaendeV1Block;

export interface PageInhaltFrueherV1Block {
  _type: "frueher";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
  "bildunterschrift"?: string | null;
}

export type PageInhaltFrueherBlock = PageInhaltFrueherV1Block;

export interface PageInhaltKassenzettelV1Block {
  _type: "kassenzettel";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
  "link"?: string | null;
}

export type PageInhaltKassenzettelBlock = PageInhaltKassenzettelV1Block;

export interface PageInhaltPreisTeaserV1Block {
  _type: "preis_teaser";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
  "link"?: string | null;
}

export type PageInhaltPreisTeaserBlock = PageInhaltPreisTeaserV1Block;

export interface PageInhaltFunktionenKopfV1Block {
  _type: "funktionen_kopf";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
}

export type PageInhaltFunktionenKopfBlock = PageInhaltFunktionenKopfV1Block;

export interface PageInhaltAbschnittV1Block {
  _type: "abschnitt";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
  "diagramm": "prognose" | "wochenvergleich" | "aktionswoche" | "wetter" | "tagesreport";
  "gespiegelt"?: boolean | null;
  "dunkel"?: boolean | null;
}

export type PageInhaltAbschnittBlock = PageInhaltAbschnittV1Block;

export interface PageInhaltAuslageV1Block {
  _type: "auslage";
  _version: 1;
  _key: string;
  "titel": string;
  "eintraege": { "name": string; "text": string }[];
}

export type PageInhaltAuslageBlock = PageInhaltAuslageV1Block;

export interface PageInhaltWegV1Block {
  _type: "weg";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
  "schritte": { "wann": string; "was": string; "text"?: string | null }[];
}

export type PageInhaltWegBlock = PageInhaltWegV1Block;

export interface PageInhaltPreiseKopfV1Block {
  _type: "preise_kopf";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
}

export type PageInhaltPreiseKopfBlock = PageInhaltPreiseKopfV1Block;

export interface PageInhaltTarifeV1Block {
  _type: "tarife";
  _version: 1;
  _key: string;
  "hinweis"?: string | null;
}

export type PageInhaltTarifeBlock = PageInhaltTarifeV1Block;

export interface PageInhaltRechnerV1Block {
  _type: "rechner";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
}

export type PageInhaltRechnerBlock = PageInhaltRechnerV1Block;

export interface PageInhaltVergleichV1Block {
  _type: "vergleich";
  _version: 1;
  _key: string;
  "titel": string;
}

export type PageInhaltVergleichBlock = PageInhaltVergleichV1Block;

export interface PageInhaltFragenV1Block {
  _type: "fragen";
  _version: 1;
  _key: string;
  "titel": string;
  "fragen": { "frage": string; "antwort": string }[];
}

export type PageInhaltFragenBlock = PageInhaltFragenV1Block;

export interface PageInhaltSchlussV1Block {
  _type: "schluss";
  _version: 1;
  _key: string;
  "titel": string;
  "text"?: string | null;
  "nachsatz"?: string | null;
}

export type PageInhaltSchlussBlock = PageInhaltSchlussV1Block;

export type PageInhaltBlock = PageInhaltEinstiegBlock | PageInhaltPinnwandBlock | PageInhaltPlanspielBlock | PageInhaltWahrheitstestBlock | PageInhaltNachtBlock | PageInhaltEinwaendeBlock | PageInhaltFrueherBlock | PageInhaltKassenzettelBlock | PageInhaltPreisTeaserBlock | PageInhaltFunktionenKopfBlock | PageInhaltAbschnittBlock | PageInhaltAuslageBlock | PageInhaltWegBlock | PageInhaltPreiseKopfBlock | PageInhaltTarifeBlock | PageInhaltRechnerBlock | PageInhaltVergleichBlock | PageInhaltFragenBlock | PageInhaltSchlussBlock;

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  inhalt?: PageInhaltBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
  }
}